// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

export interface ChatUpdate { messages?: Array<Message>, summary?: string, title?: string, }