// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

export interface Chat { id: string, messages: Array<Message>, summary: string | null, title: string, }