// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageSender } from "./MessageSender";

export interface Message { from: MessageSender, content: string, }